export const GET_RANDOM_GIF = '@gifs/GET_RANDOM_GIF';
export const GET_RANDOM_GIF_SUCCESS = '@gifs/GET_RANDOM_GIF_SUCCESS';
export const GET_RANDOM_GIF_ERROR = '@gifs/GET_RANDOM_GIF_ERROR';

export const LOAD_MULTIPLE_GIFS = '@gifs/LOAD_MULTIPLE_GIFS';
export const LOAD_MULTIPLE_GIFS_SUCCESS = '@gifs/LOAD_MULTIPLE_GIFS_SUCCESS';
export const LOAD_MULTIPLE_GIFS_ERROR = '@gifs/LOAD_MULTIPLE_GIFS_ERROR';

export const RESET = '@gifs/RESET';
