export const GET_RANDOM_GIF = '@gifs/GET_RANDOM_GIF';
export const GET_RANDOM_GIF_FULFILLED = '@gifs/GET_RANDOM_GIF_FULFILLED';
export const GET_RANDOM_GIF_REJECTED = '@gifs/GET_RANDOM_GIF_REJECTED';

export const LOAD_MULTIPLE_GIFS = '@gifs/LOAD_MULTIPLE_GIFS';
export const LOAD_MULTIPLE_GIFS_FULFILLED = '@gifs/LOAD_MULTIPLE_GIFS_FULFILLED';
export const LOAD_MULTIPLE_GIFS_REJECTED = '@gifs/LOAD_MULTIPLE_GIFS_REJECTED';

export const RESET = '@gifs/RESET';
